vendor_criteria =  {
        "vendorName": "yesbank",
        "vendorType": "PSU",
        "active": True,
        "criteria":[{"secured":{
            "cat_A":{
                "max_loan_amount": 15000000,
                "interest_rate": "11% to 11.30%",
                "max_tenure": "15 years",
                "moratorium_period": "",
                "processing_fee": "",
                "supported_degrees": ["Bachelors", "Masters", "PhD"],
                "collateral_required": True,
                "coapplicant_required": True,
                "repayment_options": ["EMI", "Interest servicing"],
                "required_admission_letter": True,
                "pre_admission_sanction": False,
                "min_10th_score": 60,
                "min_12th_score": 60,
                "min_bachelor_score": 60,
                "course_type": [],
                "max_educational_backlogs": 0,
                "own_house_required": True,
                "basic_income":[{"salaried": 25000, "self_employed": 50000}],
                "cibil_score": 700,
                "education_backlogs": 0,
                "margin_money":"15%",
                "NRI_loan": True
                },
            "cat_B":{
                "max_loan_amount": 15000000,
                "interest_rate": "11% to 11.30%",
                "max_tenure": "",
                "moratorium_period": "",
                "processing_fee": "",
                "supported_degrees": ["Bachelors", "Masters", "PhD"],
                "collateral_required": True,
                "coapplicant_required": True,
                "repayment_options": ["EMI", "Interest servicing"],
                "required_admission_letter": True,
                "pre_admission_sanction": True,
                "min_10th_score": 60,
                "min_12th_score": 60,
                "min_bachelor_score": 60,
                "course_type": [],
                "max_educational_backlogs": 0,
                "own_house_required": True,
                "basic_income":[{"salaried": 25000, "self_employed": 50000}],
                "cibil_score": 700,
                },

            "cat_C":{
                "max_loan_amount": 15000000,
                "interest_rate": "11% to 11.30%",
                "max_tenure": "",
                "moratorium_period": "",
                "processing_fee": "",
                "supported_degrees": ["Bachelors", "Masters", "PhD"],
                "collateral_required": True,
                "coapplicant_required": True,
                "repayment_options": ["EMI", "Interest servicing"],
                "required_admission_letter": True,
                "pre_admission_sanction": True,
                "min_10th_score": 60,
                "min_12th_score": 60,
                "min_bachelor_score": 60,
                "course_type": [],
                "max_educational_backlogs": 0,
                "own_house_required": True,
                "basic_income":[{"salaried": 25000, "self_employed": 50000}],
                "cibil_score": 700,
                },
            "cat_D":{
                "max_loan_amount": 15000000,
                "interest_rate": "11% to 11.30%",
                "max_tenure": "",
                "moratorium_period": "",
                "processing_fee": "",
                "supported_degrees": ["Bachelors", "Masters", "PhD"],
                "collateral_required": True,
                "coapplicant_required": True,
                "repayment_options": ["EMI", "Interest servicing"],
                "required_admission_letter": True,
                "pre_admission_sanction": True,
                "min_10th_score": 60,
                "min_12th_score": 60,
                "min_bachelor_score": 60,
                "course_type": [],
                "max_educational_backlogs": 0,
                "own_house_required": True,
                "basic_income":[{"salaried": 25000, "self_employed": 50000}],
                "cibil_score": 700,
                }
        }, "unsecured": {
            "cat_A":{
                "max_loan_amount": 15000000,
                "interest_rate": "11% to 11.30%",
                "max_tenure": "",
                "moratorium_period": "",
                "processing_fee": "",
                "supported_degrees": ["Bachelors", "Masters", "PhD"],
                "collateral_required": True,
                "coapplicant_required": True,
                "repayment_options": ["EMI", "Interest servicing"],
                "required_admission_letter": True,
                "pre_admission_sanction": True,
                "min_10th_score": 60,
                "min_12th_score": 60,
                "min_bachelor_score": 60,
                "course_type": [],
                "max_educational_backlogs": 0,
                "own_house_required": True,
                "basic_income":[{"salaried": 25000, "self_employed": 50000}],
                "cibil_score": 700,
                },
            "cat_B":{
                "max_loan_amount": 15000000,
                "interest_rate": "11% to 11.30%",
                "max_tenure": "",
                "moratorium_period": "",
                "processing_fee": "",
                "supported_degrees": ["Bachelors", "Masters", "PhD"],
                "collateral_required": True,
                "coapplicant_required": True,
                "repayment_options": ["EMI", "Interest servicing"],
                "required_admission_letter": True,
                "pre_admission_sanction": True,
                "min_10th_score": 60,
                "min_12th_score": 60,
                "min_bachelor_score": 60,
                "course_type": [],
                "max_educational_backlogs": 0,
                "own_house_required": True,
                "basic_income":[{"salaried": 25000, "self_employed": 50000}],
                "cibil_score": 700,
                },
            "cat_C":{
                "max_loan_amount": 15000000,
                "interest_rate": "11% to 11.30%",
                "max_tenure": "",
                "moratorium_period": "",
                "processing_fee": "",
                "supported_degrees": ["Bachelors", "Masters", "PhD"],
                "collateral_required": True,
                "coapplicant_required": True,
                "repayment_options": ["EMI", "Interest servicing"],
                "required_admission_letter": True,
                "pre_admission_sanction": True,
                "min_10th_score": 60,
                "min_12th_score": 60,
                "min_bachelor_score": 60,
                "course_type": [],
                "max_educational_backlogs": 0,
                "own_house_required": True,
                "basic_income":[{"salaried": 25000, "self_employed": 50000}],
                "cibil_score": 700,
                },
            "cat_D":{
                "max_loan_amount": 15000000,
                "interest_rate": "11% to 11.30%",
                "max_tenure": "",
                "moratorium_period": "",
                "processing_fee": "",
                "supported_degrees": ["Bachelors", "Masters", "PhD"],
                "collateral_required": True,
                "coapplicant_required": True,
                "repayment_options": ["EMI", "Interest servicing"],
                "required_admission_letter": True,
                "pre_admission_sanction": True,
                "min_10th_score": 60,
                "min_12th_score": 60,
                "min_bachelor_score": 60,
                "course_type": [],
                "max_educational_backlogs": 0,
                "own_house_required": True,
                "basic_income":[{"salaried": 25000, "self_employed": 50000}],
                "cibil_score": 700,
                }
        }}],
        "supported_countries": ["USA", "UK", "Australia", "Germany", "France", "Singapore", "New Zealand", "Ireland", "Netherlands", "Sweden", "Switzerland", "Italy", "Spain", "Japan", "Finland","UAE"],
        "supported_pincode": ["10001", "10002", "10003", "10004", "10005"]
        }


           
    