VENDORS = [
    {
        "vendorName": "axisbank",
        "vendorType": "Private",
        "active": True,
        "criteria": {
            "loan_options": ["Secured & Unsecured"],
            "max_secured_loan_inr": 250000000,
            "max_unsecured_loan_inr": 7500000,
            "min_loan_inr": None,
            "interest_rate_secured": "12.75%",
            "interest_rate_unsecured": "12.75%",
            "processing_fee": "1% + GST",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 6 months",
            "repayment_options": ["SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "supported_countries": [
                "US", "UK", "Canada", "Ireland", "Finland", "Denmark", "Sweden", "Spain",
                "Netherlands", "France", "Switzerland", "Belgium", "Austria", "Norway", "Poland",
                "Australia", "Newzealand", "Germany", "Singapore", "Malaysia", "Hong Kong", "Dubai"
            ],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": True,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 0,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 30,
            "Foir": [{"Salaried": "75%"}, {"Self Employed": "80%"}],
            "requires_co_applicant": True,
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 35000,
                "self_employed_inr_annual": 450000
            },
            "own_house_required": True,
            "requires_collateral": None,
            "supported_collateral_types": ["Property", "Fixed Deposit"],
            "geographical_restrictions": [],
            "interest_subsidy_eligibility": "CSIS for income < ₹4.5L",
            "cibil_score_requirement": "720+ preferred",
            "notes": "Private bank offering competitive rates, flexible collateral options."
        }
    },
    {
        "vendorName": "avanse",
        "vendorType": "NBFC",
        "active": True,
        "criteria": {
            "loan_options": ["Secured & Unsecured"],
            "max_secured_loan_inr": 20000000,
            "max_unsecured_loan_inr": 15000000,
            "min_loan_inr": None,
            "interest_rate_secured": "10.5%",
            "interest_rate_unsecured": "11.25%",
            "processing_fee": "1% to 1.5% + GST",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 1 year",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "supported_countries": [
                "US", "UK", "Canada", "Ireland", "Finland", "Denmark", "Italy", "Sweden", "Spain",
                "Netherlands", "France", "Switzerland", "Belgium", "Austria", "Norway", "Poland",
                "Greece", "Malta", "Australia", "Newzealand", "Germany", "South Africa", "Singapore",
                "Malaysia", "Hong Kong"
            ],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": True,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "Foir": "50%",
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 33,
            "requires_co_applicant": True,
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 20000,
                "self_employed_inr_annual": 300000
            },
            "own_house_required": True,
            "requires_collateral": None,
            "supported_collateral_types": ["Property", "Fixed Deposit"],
            "geographical_restrictions": ["Punjab", "Gujarat", "North Eastern States", "J&K"],
            "interest_subsidy_eligibility": "None",
            "cibil_score_requirement": "700+ preferred",
            "notes": "NBFC with flexible loan options, geographical restrictions apply."
        }
    },
    {
        "vendorName": "Tata Capital",
        "vendorType": "NBFC",
        "active": True,
        "criteria": {
            "loan_options": ["Unsecured"],
            "max_secured_loan_inr": None,
            "max_unsecured_loan_inr": 7000000,
            "min_loan_inr": 700000,
            "interest_rate_secured": None,
            "interest_rate_unsecured": "11.5%",
            "processing_fee": "1% + GST",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 1 year",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "supported_countries": [
                "US", "UK", "Canada", "Ireland", "Finland", "Denmark", "Italy", "Sweden", "Spain",
                "Netherlands", "France", "Switzerland", "Belgium", "Austria", "Norway", "Poland",
                "Ukraine", "Greece", "Malta", "Australia", "Newzealand", "Germany"
            ],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "Management"],
            "requires_admission": True,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 35,
            "requires_co_applicant": True,
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 25000,
                "self_employed_inr_annual": 300000
            },
            "own_house_required": True,
            "requires_collateral": False,
            "supported_collateral_types": False,
            "geographical_restrictions": False,
            "interest_subsidy_eligibility": "None",
            "cibil_score_requirement": "700+ preferred",
            "notes": "NBFC focused on unsecured loans, requires admission confirmation."
        }
    },
    {
        "vendorName": "unionbank",
        "vendorType": "PSU",
        "active": True,
        "criteria": {
            "loan_options": ["Secured & Unsecured"],
            "max_secured_loan_inr": 15000000,
            "max_unsecured_loan_inr": 4000000,
            "min_loan_inr": None,
            "interest_rate_secured": "9.25%",
            "interest_rate_unsecured": "9.75%",
            "processing_fee": "10000 to 20000",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 1 year",
            "repayment_options": ["SI & EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 15,
            "supported_countries": [
                "US", "UK", "Canada", "Ireland", "Finland", "Denmark", "Italy", "Sweden", "Spain",
                "Netherlands", "France", "Switzerland", "Belgium", "Austria", "Norway", "Poland",
                "Greece", "Malta", "Australia", "Newzealand", "Germany", "South Africa", "Singapore",
                "Malaysia", "Hong Kong"
            ],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": True,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 5,
            "min_ielts_score": None,
            "min_toefl_score": None,
            "min_gmat_score": None,
            "min_pte_score": None,
            "min_sat_score": None,
            "min_duolingo_score": None,
            "max_student_age": 40,
            "requires_co_applicant": True,
            "Foir": "60%",
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 20000,
                "self_employed_inr_annual": None
            },
            "own_house_required": True,
            "requires_collateral": None,
            "supported_collateral_types": ["Property", "Fixed Deposit"],
            "geographical_restrictions": [],
            "interest_subsidy_eligibility": "CSIS for income < ₹4.5L",
            "cibil_score_requirement": "None",
            "notes": "PSU bank with flexible loan options, margin money required."
        }
    },
    {
        "vendorName": "Avanse Global",
        "vendorType": "International",
        "active": True,
        "criteria": {
            "loan_options": ["Unsecured"],
            "max_secured_loan_inr": None,
            "max_unsecured_loan_usd": 125000,
            "min_loan_inr": None,
            "interest_rate_secured": None,
            "interest_rate_unsecured": [{"Stem": "10.5% to 13.5%"}, {"Management": "11% to 14%"}],
            "processing_fee": "2.5% + GST",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 6 months",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "supported_countries": ["US"],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "Management"],
            "requires_admission": True,
            "min_academic_score_percentage": None,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 55,
            "requires_co_applicant": False,
            "supported_co_applicant_relations": None,
            "basic_income_norms": None,
            "own_house_required": False,
            "requires_collateral": False,
            "supported_collateral_types": False,
            "geographical_restrictions": False,
            "interest_subsidy_eligibility": "None",
            "cibil_score_requirement": "700+ preferred",
            "notes": "International lender for US only, no co-applicant required."
        }
    },
    {
        "vendorName": "HDFC Credila",
        "vendorType": "NBFC",
        "active": True,
        "criteria": {
            "loan_options": ["Secured & Unsecured"],
            "max_secured_loan_inr": 30000000,
            "max_unsecured_loan_inr": 7500000,
            "min_loan_inr": None,
            "interest_rate_secured": "10.25%",
            "interest_rate_unsecured": "11%",
            "processing_fee": "1% + GST",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 6 months",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "supported_countries": [
                "US", "UK", "Ireland", "Germany", "Canada", "Australia", "Newzealand",
                "South Africa", "Singapore", "Malaysia", "Hong Kong", "Dubai", "Rest of Europe"
            ],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": [
                {"Conditional Admission": True}, {"Admission letter not recived": False}, {"Admission Letter": True}
            ],
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 35,
            "requires_co_applicant": True,
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 35000,
                "self_employed_inr_annual": 450000
            },
            "own_house_required": False,
            "requires_collateral": None,
            "supported_collateral_types": ["Property", "Fixed Deposit"],
            "geographical_restrictions": [],
            "interest_subsidy_eligibility": "None",
            "cibil_score_requirement": "700+ preferred",
            "notes": "NBFC with wide country support, competitive rates."
        }
    },
    {
        "vendorName": "InCred",
        "vendorType": "NBFC",
        "active": True,
        "criteria": {
            "loan_options": ["Unsecured"],
            "max_secured_loan_inr": None,
            "max_unsecured_loan_inr": 10000000,
            "min_loan_inr": 1500000,
            "interest_rate_secured": None,
            "interest_rate_unsecured": "11%",
            "processing_fee": "0.75% + GST",
            "loan_tenor_years": "13 to 15",
            "moratorium_period": "Course duration + 1 year",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "supported_countries": ["US", "Canada", "Germany", "France", "UK", "Newzealand"],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": False,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 33,
            "requires_co_applicant": True,
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 25000,
                "self_employed_inr_annual": 300000
            },
            "own_house_required": False,
            "requires_collateral": False,
            "supported_collateral_types": [],
            "geographical_restrictions": ["J&K", "North Eastern States"],
            "interest_subsidy_eligibility": "None",
            "cibil_score_requirement": "700+ preferred",
            "notes": "NBFC with unsecured focus, geographical restrictions apply."
        }
    },
    {
        "vendorName": "IDFC Bank",
        "vendorType": "Private",
        "active": True,
        "criteria": {
            "loan_options": ["Secured", "Unsecured"],
            "max_secured_loan_inr": 20000000,
            "max_unsecured_loan_inr": 10000000,
            "min_loan_inr": 700000,
            "interest_rate_secured": "9%",
            "interest_rate_unsecured": "11%",
            "processing_fee": "1% + GST",
            "loan_tenor_years": 12,
            "moratorium_period": "Course duration + 1 year",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "Foir": [{"Salaried": "50%"}, {"Self Employed": "60%"}],
            "supported_countries": [
                "US", "UK", "Ireland", "Germany", "Canada", "Australia", "Newzealand",
                "South Africa", "Singapore", "Malaysia", "Hong Kong"
            ],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": False,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 30,
            "requires_co_applicant": True,
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 30000,
                "self_employed_inr_annual": 600000
            },
            "own_house_required": True,
            "requires_collateral": None,
            "supported_collateral_types": ["Property", "Fixed Deposit"],
            "geographical_restrictions": ["Serviceable pincodes only"],
            "interest_subsidy_eligibility": "CSIS for income < ₹4.5L",
            "cibil_score_requirement": "700+ preferred",
            "notes": "Private bank with pincode restrictions, competitive rates."
        }
    },
    {
        "vendorName": "yesbank",
        "vendorType": "Private",
        "active": True,
        "criteria": {
            "loan_options": ["Secured", "Unsecured"],
            "max_secured_loan_inr": 15000000,
            "max_unsecured_loan_inr": 7500000,
            "min_loan_inr": 700000,
            "interest_rate_secured": "10.5%",
            "interest_rate_unsecured": "11.5%",
            "processing_fee": "1% + GST",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 6 months",
            "repayment_options": ["SI", "EMI", "PSI"],
            "prepayment_penalty": "None",
            "Foir": "60%",
            "margin_money_percentage": 10,
            "supported_countries": [
                "US", "UK", "Ireland", "Germany", "Canada", "Australia", "Newzealand",
                "South Africa", "Singapore", "Malaysia", "Hong Kong", "Dubai"
            ],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": False,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 30,
            "requires_co_applicant": True,
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 35000,
                "self_employed_inr_annual": 450000
            },
            "own_house_required": True,
            "requires_collateral": None,
            "supported_collateral_types": ["Property", "Fixed Deposit"],
            "geographical_restrictions": [],
            "interest_subsidy_eligibility": "CSIS for income < ₹4.5L",
            "cibil_score_requirement": "700+ preferred",
            "notes": "Private bank with margin money requirement."
        }
    },
    {
        "vendorName": "Bank of Maharashtra",
        "vendorType": "PSU",
        "active": True,
        "criteria": {
            "loan_options": ["Secured"],
            "max_secured_loan_inr": 25000000,
            "max_unsecured_loan_inr": None,
            "min_loan_inr": None,
            "interest_rate_secured": "9.75%",
            "interest_rate_unsecured": None,
            "processing_fee": "0.5%",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 1 year",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 15,
            "supported_countries": [],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": False,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 30,
            "requires_co_applicant": True,
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 20000,
                "self_employed_inr_annual": None
            },
            "own_house_required": False,
            "requires_collateral": True,
            "supported_collateral_types": ["Property", "Fixed Deposit"],
            "geographical_restrictions": [],
            "interest_subsidy_eligibility": "CSIS for income < ₹4.5L",
            "cibil_score_requirement": "None",
            "notes": "PSU bank, secured loans only, margin money required."
        }
    },
    {
        "vendorName": "bankofbaroda",
        "vendorType": "PSU",
        "active": True,
        "criteria": {
            "loan_options": ["Secured"],
            "max_secured_loan_inr": 15000000,
            "max_unsecured_loan_inr": None,
            "min_loan_inr": None,
            "interest_rate_secured": "9.7%",
            "interest_rate_unsecured": None,
            "processing_fee": "₹10000",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 1 year",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 15,
            "supported_countries": [
                "US", "UK", "Ireland", "Germany", "Canada", "Australia", "Newzealand",
                "South Africa", "Singapore", "Malaysia", "Hong Kong", "All countries"
            ],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": False,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 30,
            "Foir": "50%",
            "requires_co_applicant": True,
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 20000,
                "self_employed_inr_annual": None
            },
            "own_house_required": False,
            "requires_collateral": True,
            "supported_collateral_types": ["Property", "Fixed Deposit"],
            "geographical_restrictions": [],
            "interest_subsidy_eligibility": "CSIS for income < ₹4.5L",
            "cibil_score_requirement": "None",
            "notes": "PSU bank, secured loans up to ₹150L, margin money required."
        }
    },
    {
        "vendorName": "Prodigy",
        "vendorType": "International",
        "active": True,
        "criteria": {
            "loan_options": ["Unsecured"],
            "max_secured_loan_inr": None,
            "max_unsecured_loan_inr": 18600000,
            "min_loan_inr": None,
            "interest_rate_secured": None,
            "interest_rate_unsecured": "9.99%",
            "processing_fee": "5% on disbursement",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 6 months",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "supported_countries": ["US", "UK", "Australia", "Ireland", "France"],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": True,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 55,
            "requires_co_applicant": False,
            "supported_co_applicant_relations": None,
            "basic_income_norms": None,
            "own_house_required": False,
            "requires_collateral": False,
            "supported_collateral_types": [],
            "geographical_restrictions": [],
            "interest_subsidy_eligibility": "None",
            "cibil_score_requirement": "700+ preferred",
            "notes": "International lender, no co-applicant required."
        }
    },
    {
        "vendorName": "mpower",
        "vendorType": "International",
        "active": True,
        "criteria": {
            "loan_options": ["Unsecured"],
            "max_secured_loan_inr": None, 
            "max_unsecured_loan_usd": 1000000,
            "min_loan_inr": 700000,
            "interest_rate_secured": None,
            "interest_rate_unsecured": "12.99% ",
            "processing_fee": "5%",
            "loan_tenor_years": 10,
            "moratorium_period": "Course duration + 6 months",
            "repayment_options": ["SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "supported_countries": ["US", "Canada"],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": True,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 55,
            "requires_co_applicant": False,
            "supported_co_applicant_relations": None,
            "basic_income_norms": None,
            "own_house_required": False,
            "requires_collateral": False,
            "supported_collateral_types": [],
            "geographical_restrictions": [],
            "interest_subsidy_eligibility": "None",
            "cibil_score_requirement": "700+ preferred",
            "notes": "International lender for US/Canada, min loan ₹1.66L."
        }
    },
    {
        "vendorName": "Punjab National Bank",
        "vendorType": "PSU",
        "active": True,
        "criteria": {
            "loan_options": ["Secured"],
            "max_secured_loan_inr": 50000000,
            "max_unsecured_loan_inr": None,
            "min_loan_inr": None,
            "interest_rate_secured": "10.5%",
            "interest_rate_unsecured": None,
            "processing_fee": None,
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 1 year",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "supported_countries": [
                "US", "UK", "Canada", "Ireland", "Finland", "Denmark", "Italy", "Sweden", "Spain",
                "Netherlands", "France", "Switzerland", "Belgium", "Austria", "Norway", "Poland",
                "Ukraine", "Greece", "Malta", "Australia", "Newzealand", "Germany", "South Africa",
                "Singapore", "Malaysia", "Hong Kong", "All countries"
            ],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": True,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 30,
            "requires_co_applicant": True,
            "supported_co_applicant_relations": ["Father", "Mother", "Husband", "Wife", "Brother", "Sister"],
            "basic_income_norms": {
                "salaried_inr_monthly": 20000,
                "self_employed_inr_annual": None
            },
            "own_house_required": False,
            "requires_collateral": True,
            "supported_collateral_types": ["Property", "Fixed Deposit"],
            "geographical_restrictions": [],
            "interest_subsidy_eligibility": "CSIS for income < ₹4.5L",
            "cibil_score_requirement": "None",
            "notes": "PSU bank with high secured loan limit, competitive rates."
        }
    },
    {
        "vendorName": "auxilo",
        "vendorType": "NBFC",
        "active": True,
        "criteria": {
            "loan_options": ["Secured", "Unsecured"],
            "max_secured_loan_inr": 20000000,
            "max_unsecured_loan_inr": 10000000,
            "min_loan_inr": 700000,
            "interest_rate_secured": "11%",
            "interest_rate_unsecured": "11.25%",
            "processing_fee": "1%",
            "loan_tenor_years": 15,
            "moratorium_period": "Course duration + 1 year",
            "repayment_options": ["PSI", "SI", "EMI"],
            "prepayment_penalty": "None",
            "margin_money_percentage": 0,
            "supported_countries": [
                "US", "UK", "Ireland", "Germany", "Canada", "Australia", "Newzealand",
                "Rest of Europe", "Singapore"
            ],
            "supported_degrees": ["Master's", "Bachelor's", "Diploma","PhD"],
            "supported_courses": ["Stem", "NonStem", "Management"],
            "requires_admission": False,
            "min_academic_score_percentage": 60,
            "max_educational_backlogs": 15,
            "min_ielts_score": 6,
            "min_toefl_score": 80,
            "min_gmat_score": 400,
            "min_pte_score": 51,
            "min_sat_score": 1000,
            "min_duolingo_score": 106,
            "max_student_age": 30,
            "requires_co_applicant": True,
            "supported_co_applicant_relations": [
                "Father", "Mother", "Husband", "Wife", "Brother", "Sister", "1st Cousin",
                "Uncle", "Aunt", "Father in Law", "Mother in Law", "Brother in Law"
            ],
            "basic_income_norms": {
                "salaried_inr_monthly": 25000,
                "self_employed_inr_annual": 300000
            },
            "own_house_required": True,
            "requires_collateral": None,
            "supported_collateral_types": ["Property", "Fixed Deposit"],
            "geographical_restrictions": ["Uttar Pradesh", "Bihar", "North Eastern States", "J&K", "Kerala"],
            "interest_subsidy_eligibility": "None",
            "cibil_score_requirement": "700+ preferred",
            "notes": "NBFC with flexible loan options, geographical restrictions apply."
        }
    }
]
